import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import "normalize.css";
import "swiper/css";

import Header from "./layouts/header/header";

const manropeSans = Manrope({
  variable: "--font-geist-sans",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={manropeSans.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
